hl.c, ll.c
Avoids repeated decompression, allowing the kernel's vfs cache to function for pages already decompressed.
=> Improve performance by enabling vfs cache

fuseprivate.c
size of a symlink in "stat" structure should be the link target string size
=> symlinks do have a size

Makefile.am, README, extract.c
The squashfuse_extract can extract files, directories, and symlinks from a squashfs image. Closes #13 and partly #9.
=> Add squashfuse_extract tool

CONFIGURATION, Makefile.am, configure.ac, decompress.c, squashfs_fs.h
* Zstd support has been added to SquashFS in the kernel in commit https://github.com/torvalds/linux/commit/87bf54bb43ddd385d2538b777324bf737f243042.
* Support is ready for `mksquashfs` and is coming to squashfs-tools soon https://sourceforge.net/p/squashfs/mailman/message/35996905/.
=> Add zstd compression support

Makefile.am, configure.ac, squashfuse.pc.in
I leave squashfuse.pc.in's Requires empty since i want to do short and easy to review PR. It won't break anything for the moment, and i'm continuing on the packaging of squashfuse for nixos distribution.
=> Introduce to squashfuse.pc.in

.gitignore, configure.ac, fuseprivate.h, ll.c
If specified via the timeout option (-o timeout=N), then squashfuse_ll
will track the time of all accesses as well as the count of open files
and directories.  If the open count is zero and more seconds than the
specified timeout have passed since the last activity on the
filesystem, then we exit.
The approach is based on fuse's own signal handling (from
lib/fuse_signals.c).
=> Add support for an idle timeout when mounting a squashfile.

cache.c, cache.h, fs.c
The root issue is sqfs_cache_add always reserved an allocated space
before a read failure occurred.  When the failure then happened, the
entry was still "alive" and later would be discarded, causing
segfaults.
Now when these failures occur, we mark the entry as invalid.  Since
"in-place construction" didn't complete, we don't call discard.
This crash was reproducible by simply adding a `return SQFS_ERR;` in
`sqfs_data_block_read`.  Before this fix, the process would crash (and
ASAN would verify this); with this fix, the process stays up and the
caller receives an `Input/output error` instead.
=> Fix segfault when failures to read occur

hl.c, ll.c
The offset field in sqfs_opts has type size_t, so the scanf string needs to be %zu instead of %u, or the field length might mismatch.
Note that %zu is C99; an alternate solution would be to keep %u and change the type of the field to "unsigned" instead.  (Or use "%lu" and make the field "unsigned long".)
=> Fix scan format for offset option

Makefile.am, squashfuse.pc.in
The install process currently installs only `squashfuse.h` and `squashfs_fs.h`, directly into `PREFIX/include/`.
Unfortunately, because the contents of `squashfuse.h` is only:
https://github.com/vasi/squashfuse/blob/0b48352ed7a89d920bb6792ac59f9f6775088f02/squashfuse.h#L28-L33
it is useless without those other files, and the installation is broken (cannot be compiled against).
This PR adds all of the listed headers, plus any `#include`d by _those_ headers, to the `pkgconfigdir_HEADERS` list, and sets `pkgconfigdir = @includedir@/squashfuse`. This means that all of the necessary headers will be installed in `PREFIX/include/squashfuse/` and they can be referenced at that path to build software that links against the library.
The `squashfuse.pc.in` file is also updated to point `includedir` …
=> Move headers to subdir of include/, install missing headers

.cirrus.yml
This currently only builds, because it appears the tests do not yet run
on FreeBSD (issue #41).
=> Add Cirrus-CI config for FreeBSD CI

dir.c
tar2sqfs produces squash files, where empty directories have a dir_size of 0, which leads to a integer overflow.
=> handle empty directories correctly

Makefile.am, configure.ac, swap.c, swap.h, tests/endiantest.c
Updated from original pull request to get rid of google test dependency - test cases are so simple there is no need for a test framework at all, just simple binary that returns non-zero on failure.
=> Use optimized linux byteswap macros if available.

ll.c
If any of the first three file descriptors are closed when squashfuse is
launched, it will get a fd <= 2 when it opens the squashfs image file.
Unfortunately fuse_daemonize() from libfuse unconditionally clobbers fds 0-2
by dup2-ing /dev/null over them. This made the squashfuse image inaccessible
and things went very poorly.
Fix by simply making sure fds 0-2 are open before calling sqfs_ll_open() so
it is guaranteed to get a safe fd.
Reproduction (previously failed with "No such file or directory", now
succeeds):
0<&- squashfuse_ll fs.image /tmp/crap
ls /tmp/crap
=> Fix "No such file or directory" when launched with empty fd 0.

ll.c
repeatedly looking up non-existent files.
=> Negative cache failed lookups. This saves a FUSE operation when

.cirrus.yml, .github/workflows/ci.yml, .gitignore, .travis.yml, Makefile.am, configure.ac, ll.c, ll.h, ll_main.c, squashfuse_ll.pc.in
This makes it easier for people to statically link squashfuse_ll into
their application, which can in turn be used to more easily ship
self-exectracting binaries (e.g. facebook xar or appimage)
=> Split squashfuse_ll into a lib and executable

xattr.c
I found that when selinux is enabled when mksquashfs is run, it adds an extended attribute that the kernel squashfs shows (in an strace of attr -l) as `security.selinux`, but squashfuse shows it as `trusted.selinux`.  That's because the extended attribute types for trusted and selinux as defined in [squashfs_fs.h](https://github.com/vasi/squashfuse/blob/0.1.105/squashfs_fs.h#L97) are defined as 1 & 2, respectively, but their names as listed in [xattr.c](https://github.com/vasi/squashfuse/blob/0.1.105/xattr.c#L44) are reversed.  As a result, attempts to look at that attribute (for example with strace -l) returns an ENODATA error.
This corrects the order of the two prefixes.
=> Correct the order of xattr prefixes, swapping trusted and security

m4/squashfuse_fuse.m4
The test did not check the number of arguments with certain fuse headers because they declare fuse_mount in <fuse.h>, not <fuse_lowlevel.h>.  If the compile supports implicit function declarations, the test always succeeds (regardless of parameter count).  If it does not, it always fails.
Found as part of:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
=> Fix fuse_mount function argument probing

Makefile.am, cache.c, cache.h, cache_mt.c, common.h, configure.ac, file.c, file.h, fs.c, fs.h, ll.c, ll_main.c, m4/squashfuse_c.m4, squashfs_fs.h, table.c, tests/cachetest.c, tests/ll-smoke-singlethreaded.sh, tests/ll-smoke.sh, tests/umount-test.sh.in
Third time's the charm :)
Rebased the multi-threading patches over the big ll refactor, tested.
Added a bonus changeset to improve SIGTERM handling; previously if a squashfuse process received a SIGTERM the process just exited immediately and filesystem users would hang or crash. Now it does a lazy unmount instead.
- Fixes #66
=> Multithreaded rebase 2

fs.h, fuseprivate.c, fuseprivate.h, hl.c, ll_main.c, stat.c
This adds `uid=N` and `gid=N` options to `squashfuse_ll` only, and improves the help message to include the options implemented outside of the FUSE options.  It is similar to long-pending PR #20, but in the meanwhile the high level api FUSE library now supports those options directly, but the low level api does not.  See [this summary of the FUSE options](https://www.fsl.cs.stonybrook.edu/docs/fuse/fuse-article-appendices.html).  PR #20 also supports using names, but the FUSE library doesn't so this matches the FUSE library.
This is [needed by Apptainer](https://github.com/apptainer/apptainer/issues/736) so the files that are mapped by an unprivileged user namespace don't end showing as the owner of `nobody`, which interferes with programs like ssh which require configuration files to be …
=> Add low-level uid=N and gid=N options, better help

.github/workflows/ci.yml
I noticed that test-suite.log was not getting uploaded, so just upload *.log.
=> upload all logs from CI check

.cirrus.yml, .github/workflows/ci.yml
In particular if the ll-smoke.sh fails it indicates there could be a helpful log in /tmp.
=> Also save any logs from /tmp

configure.ac, fuseprivate.c
This enables multithreading in squashfuse_ll by default, and when multithreading is disabled it removes the multithreading-related help options.  I think it's OK for the man page to describe the default so I didn't change that.
- Fixes #93
- Fixes #94
=> Enable low-level multithreading by default

.gitignore
This PR adds the following entries to `.gitignore`, to avoid "uncommitted changes" after build:
```
ci/features
tests/lib.sh
tests/ll-smoke.sh
tests/umount-test.sh
```
Fixes #101
=> add missing entries to .gitignore

NEWS, configure.ac
Supersedes #103 in order to force re-running freebsd check.
=> update to 0.3.0

dir.c, dir.h, extract.c, fs.c, fs.h, hl.c, ll.c, ll.h, ll_main.c, ls.c, util.c, util.h
`subdir` argument inroduced in 53e1b97 broke multiple applications depending on squashfuse.
To fix this functions that accept `subdir` arg now have `_with_subdir` suffix in them.
The old (unsuffixed) functions were reimplemented to call their `_with_subdir` counterparts with `subdir = NULL`.
Tested against libappimage (git commit `e56c21b5387fde92cbb91c835e7aa16ab60b3879`).
Fixes: #105
=> Restore functions signatures

fuseprivate.c, fuseprivate.h, ll.h, m4/squashfuse_fuse.m4, nonstd-daemon.c
We should look in the path that pkg-config gives us, not the default search paths.
Fixes #108
=> Fix header paths for fuse3

fs.h, fuseprivate.c, fuseprivate.h, hl.c, ll.c, ll.h, ll_main.c, squashfuse.1, tests/ll-smoke.sh.in
Add the notify_pipe option which allows the user to specify the path to a named pipe. When the mountpoint is ready, a message will be written to this pipe: 's' for success and 'f' for failure. To avoid blocking the fuse process until the pipe is read, a new process is spawned which performs a blocking operation on the pipe. In case of mount failure, no additional process is created and the main process blocks until the pipe is read.
An example of operation is provided below:
```
set -x
FIFO=$(mktemp -u)
mkfifo "$FIFO"
./squashfuse_ll -o notify_pipe="$FIFO" -f /path/to/squashfs/archive /tmp/squash&
STATUS=$(head -c1 "$FIFO")
if [ "$STATUS" = "s" ]; then
echo "Mountpoint contains:"
ls /tmp/squash
else
echo "Mounting squashfuse on /tmp/squash failed"
fi
```
Fixes #49
=> Add a notification mechanism for signaling when the mountpoint is ready

Makefile.am, fuseprivate.c, hl.c, tests/lib.sh.in, tests/ll-smoke.sh.in, tests/notify_test.sh
The following scenario now correctly sends a failure notification to the pipe:
```
$ mkfifo /tmp/notify_pipe
$ cat /tmp/notify_pipe
```
then run squashfuse:
```
$ ./squashfuse -o notify_pipe=/tmp/notify_pipe /dev/null /mnt
```
This fix only applies to squashfuse, squashfuse_ll was behaving as expected.
Fixes #112
=> Fix the notification pipe for squashfuse in case of failure

README
* Notes that this works on Ubuntu 22.04
* Updates the dependencies to FUSE 3
* Installs all compression algorithms, because why not?
* Installs fio and runs tests
* Calling each one of autotools individually is annoying, we should just use the autogen.sh script that we already have
We could plausibly separate this into a simple minimal release-based build (just configure/make), and a full multi-algorithm master-based build with tests. But not sure it's worth it.
=> update ubuntu build example

.github/workflows/ci.yml, .gitignore, Makefile.am, README, configure.ac, tests/ll-smoke-singlethreaded.sh.in
* Add extra dependencies to README example, it should work now in a docker ubuntu:jammy container
* While testing that this was fixed, noticed that out-of-tree builds and tests from release tarballs are both broken!
* Added some missing files to the dist tarball
* Made ll-smoke-singlethreaded aware of where ll-smoke lives, so it can be run out of tree
* Added a new test to enforce that dist builds are working
=> Fix example + distcheck

.github/workflows/ci.yml
This fixes ci failures seen after merging the last PR into the master branch.
=> Do apt-get update before any installs

.cirrus.yml
Switch the freebsd check from version 12-3, which is no longer supported, to 14-0, the latest version.
=> Update to freebsd-14-0

ll.c, ll.h, m4/squashfuse_fuse.m4
This fixes 32 bit compiles on Fedora 40.  Without it, this compiler error shows:
```
+ make squashfuse_ll
CC       squashfuse_ll-ll_main.o
ll_main.c: In function ‘main’:
ll_main.c:164:41: error: assignment to ‘void (*)(struct fuse_req *, fuse_ino_t,  uint64_t)’ {aka ‘void (*)(struct fuse_req *, long long unsigned int,  long long unsigned int)’} from incompatible pointer type ‘void (*)(struct fuse_req *, fuse_ino_t,  long unsigned int)’ {aka ‘void (*)(struct fuse_req *, long long unsigned int,  long unsigned int)’} [-Wincompatible-pointer-types]
164 |         sqfs_ll_ops.forget              = sqfs_ll_op_forget;
|                                         ^
make: *** [Makefile:1373: squashfuse_ll-ll_main.o] Error 1
```
=> Fix 32 bit compile on Fedora 40

configure.ac, hl.c, ll.c
FUSE-T is an implementation of FUSE for macOS, which is becoming popular. But squashfuse doesn't work with FUSE-T, erroring when directories are listed. This is due to FUSE-T supplying improper `offset` values to the FUSE readdir ops.
Now, squashfuse can be built with `--enable-broken-directory-offsets` to fix this behavior.
FUSE readdir ops (both high-level and low-level) return lists of directory entries. Each returned entry has an `off` field, whose value is arbitrary, entirely up to the filesystem. Subsequent calls to readdir can supply one of these offsets to continue reading from the middle of a directory.
In squashfuse, we return as `off` an offset into the squashfs internal directory entries. This lets us quickly jump to the right entry using the squashfs directory index, without …
=> Allow handling broken directory offsets

.github/workflows/ci.yml, autogen.sh
We're getting errors because of homebrew's migration from pkg-config to pkgconf: https://github.com/Homebrew/homebrew-core/pull/194885
To solve:
* Enable pkgconf in general, we'd prefer it to the ancient pkg-config
* For now, just wipe pkg-config from the macos running, and then update so we get the new pkgconf version that replaces it
* Eventually, Github will upgrade their runner so it has pkgconf, and we'll get to remove the brew remove/update
Error:
```
==> Pouring pkgconf--2.3.0_1.arm64_sonoma.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
brew unlink pkg-config@0.29.2 …
```
=> Fix macOS CI failure
